# Generated by Django 5.2.1 on 2025-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='myskills/')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
                ('rangecolor', models.CharField(max_length=50)),
            ],
        ),
    ]
