# Generated by Django 5.2.1 on 2025-06-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projesturl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectURl',
        ),
    ]
