# Generated by Django 5.2.1 on 2025-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='services/')),
                ('title', models.CharField(max_length=255)),
                ('contant', models.TextField()),
            ],
        ),
    ]
