# Generated by Django 5.2.1 on 2025-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('connect', 'Connect'), ('hiring', 'Hiring'), ('freelance', 'Freelance')], max_length=20, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
