# Generated by Django 5.2.1 on 2025-05-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], max_length=10)),
                ('colors', models.JSONField()),
            ],
        ),
    ]
