# Generated by Django 5.2.1 on 2025-05-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mynamebefore', models.CharField(max_length=100)),
                ('mynamebeAfter', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('detailcontant', models.TextField()),
                ('mypic1', models.ImageField(upload_to='detail_images/')),
                ('mypic2', models.ImageField(upload_to='detail_images/')),
            ],
        ),
    ]
